apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-replicaset
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---
apiVersion: v1
kind: Pod
metadata:
 name: pritesh-queue
 labels:
   app: queue 
   release: '1' 
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-queue:release1
